/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function registerToolboxs () {
    return `
<category name="%{BKY_GASSENSOR_CATEGORY}" id="GASSENSOR_CATEGORY" colour="#607D8B" secondaryColour="#455A64" iconURI="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MCA0MCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIj48Y2lyY2xlIGN4PSIyMCIgY3k9IjIwIiByPSIyMCIgZmlsbD0iIzYwN0Q4QiIvPjxwYXRoIGQ9Ik03IDI0IFE3IDE3IDEzIDE3IFExNCAxMiAyMCAxMiBRMjYgMTIgMjcgMTcgUTMzIDE3IDMzIDI0IFEzMyAzMCAyNyAzMCBIMTMgUTcgMzAgNyAyNHoiIGZpbGw9IiNGRkUwQjIiIHN0cm9rZT0iI2ZmZiIgc3Ryb2tlLXdpZHRoPSIwLjgiLz48cGF0aCBkPSJNMTIgMjMgUTE0IDE4IDE3IDIxIFExOC41IDE2IDIyIDE5IFEyNCAxNiAyNyAyMSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjZTUzOTM1IiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIvPjxwYXRoIGQ9Ik0yMCA2IEwxOS41IDEyIiBzdHJva2U9IiNmZmYiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtZGFzaGFycmF5PSIyIDIiLz48cGF0aCBkPSJNMTQgOCBMMTQuNSAxMiIgc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtZGFzaGFycmF5PSIyIDIiLz48cGF0aCBkPSJNMjYgOCBMMjUuNSAxMiIgc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtZGFzaGFycmF5PSIyIDIiLz48L3N2Zz4K">
    <block type="gasSensor_read" id="gasSensor_read">
        <field name="PIN">34</field>
    </block>
</category>`;
}

exports = registerToolboxs;
